[workspace]
members = [
    "worterbuch-common",
    "worterbuch-client",
    "worterbuch",
    "worterbuch-cluster-orchestrator",
    "worterbuch-cli",
    "worterbuch-speedtest",
]
resolver = "3"

[workspace.dependencies]
# Internal crates
worterbuch-common = { version = "1.7.0-alpha.1", path = "worterbuch-common" }
worterbuch-client = { version = "1.7.0-alpha.1", path = "worterbuch-client" }

async-stream = "0.3.4"
axum = "0.8.7"
axum-extra = "0.12.2"
axum-server = "0.8.0"
base64 = "0.23.1"
chrono = "0.4.45"
clap = "4.6.6"
dotenvy = "0.15.7"
flate2 = "1.1.10"
futures = "0.3.34"
futures-core = "0.3.34"
futures-util = { version = "0.3.27", default-features = false }
gethostname = "1.0.0"
getrandom = "0.4.3"
hashbrown = "0.17.1"
hashlink = "0.12.1"
headers = "0.4.1"
hex = "0.4.3"
hostname = "0.4.0"
http = "1.5.0"
http-body-util = "0.1.5"
inferno = "0.12.8"
jemalloc_pprof = { version = "0.9.0", features = ["flamegraph"] }
jsonwebtoken = "11.0.0"
lazy_static = "1.5.0"
libc = "0.2.189"
mappings = "0.7.0"
miette = "7.5.0"
mio = { version = "1.2.2", default-features = false }
opentelemetry = "0.32.0"
opentelemetry_sdk = "0.32.1"
opentelemetry-appender-tracing = "0.32.0"
opentelemetry-otlp = "0.32.0"
opentelemetry-resource-detectors = "0.12.0"
opentelemetry-semantic-conventions = "0.32.1"
pprof_util = { version = "0.8.0", features = ["flamegraph"] }
rand = "0.10.2"
random_word = { version = "0.5.0", features = ["en"] }
redb = "4.2.0"
regex = "1.13.0"
rusqlite = { version = "0.40.2", features = ["bundled"] }
schemars = "1.2.2"
serde = "1.0.229"
serde_json = "1.0.151"
serde_repr = "0.1.21"
serde_yaml = "0.9.34"
sha2 = "0.11.0"
socket2 = { version = "0.6.5", features = ["all"] }
strum = { version = "0.28.0", features = ["derive"] }
supports-color = "3.0.2"
thiserror = "2.0.20"
tikv-jemalloc-ctl = { version = "0.7.0", features = ["stats"] }
tikv-jemallocator = { version = "0.7.0", features = [
    "profiling",
    "unprefixed_malloc_on_supported_platforms",
] }
tokio = "1.53.1"
tokio-metrics = "0.5.2"
tokio-process-terminate = "0.3.2"
tokio-stream = "0.1.19"
tokio-tungstenite = "0.30.0"
tokio-tungstenite-wasm = "0.9.0"
tosub = "1.1.5"
tower-http = "0.7.0"
tracing = "0.1.41"
tracing-opentelemetry = "0.33.0"
tracing-subscriber = "0.3.20"
tungstenite = "0.30.0"
turso = "0.7.2"
uuid = "1.26.0"

[profile.release]
lto = "fat"
codegen-units = 1
# panic = "abort"
# strip = true
# debug = 0
opt-level = 3
