nodes:
  - nodeId: alice
    address: 127.0.0.1:1337
  - nodeId: bob
    address: 127.0.0.1:1338
  - nodeId: carl
    address: 127.0.0.1:1339
  # - nodeId: dave
  #   address: 127.0.0.1:1340
  # - nodeId: emily
  #   address: 127.0.0.1:1341
