version: "2"

services:
  worterbuch:
    image: babymotte/worterbuch:0.4.1-armv7
    hostname: worterbuch
    container_name: worterbuch
    restart: always
    ports:
      - 4242:4242
      - 8080:8080
    volumes:
      - ./data:/data
    logging:
      options:
        max-size: "10M"
        max-file: "5"
