version: "2"

services:
  worterbuch:
    image: babymotte/worterbuch:0.3.0-armv7
    hostname: worterbuch
    container_name: worterbuch
    restart: always
    ports:
      - 4242:4242
      - 4243:4243
      - 8080:8080
    environment:
      - RUST_LOG=info
      - WORTERBUCH_BIND_ADDRESS=0.0.0.0
    volumes:
      - ./data:/data
    logging:
      options:
        max-size: "10M"
        max-file: "5"
