version: "2"

services:
  worterbuch:
    image: babymotte/worterbuch:0.42.3
    hostname: worterbuch
    container_name: worterbuch
    restart: always
    ports:
      - 9090:9090
      - 80:80
    volumes:
      - ./data:/data
    logging:
      options:
        max-size: "10M"
        max-file: "5"
