apiVersion: v1
kind: Service
metadata:
  name: {{ include "worterbuch-cluster.fullname" . }}-internal
  labels:
    {{- include "worterbuch-cluster.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port.clusterSync }}
      targetPort: cluster-sync
      protocol: TCP
      name: cluster-sync
    - port: {{ .Values.service.port.raft }}
      targetPort: raft
      protocol: UDP
      name: raft
    - port: {{ .Values.service.port.stats }}
      targetPort: stats
      protocol: TCP
      name: stats
  selector:
    {{- include "worterbuch-cluster.selectorLabels" . | nindent 4 }}
  publishNotReadyAddresses: true
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "worterbuch-cluster.fullname" . }}-leader
  labels:
    {{- include "worterbuch-cluster.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port.http }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.port.tcp }}
      targetPort: tcp
      protocol: TCP
      name: tcp
  selector:
    {{- include "worterbuch-cluster.selectorLabels" . | nindent 4 }}
  publishNotReadyAddresses: false
