deployment:
  name: alice

ingress:
  enabled: true
  hosts:
    - host: wb.homelab
      paths:
        - path: /
          pathType: Prefix

service:
  type: NodePort
  port:
    httpNodePort: 30081
    tcpNodePort: 30091
    statsNodePort: 30084
