deployment:
  name: bob

ingress:
  enabled: true
  hosts:
    - host: wb.homelab
      paths:
        - path: /
          pathType: Prefix

service:
  type: NodePort
  port:
    httpNodePort: 30082
    tcpNodePort: 30092
    statsNodePort: 30085
