deployment:
  name: carl

ingress:
  enabled: true
  hosts:
    - host: wb.homelab
      paths:
        - path: /
          pathType: Prefix

service:
  type: NodePort
  port:
    httpNodePort: 30083
    tcpNodePort: 30093
    statsNodePort: 30086
