[package]
name = "worterbuch-common"
version = "0.30.0"
edition = "2021"
authors = ["Michael Bachmann <mbachmann@bbmsoft.net>"]
description = "Client library for Wörterbuch."
repository = "https://github.com/babymotte/worterbuch"
readme = "README.md"
license = "MIT"
keywords = ["message", "broker", "data", "base", "pubsub"]
categories = ["database"]

[dependencies]
tokio = { version = "1.20.1", features = ["sync"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.82"
tungstenite = "0.18.0"
