[package]
name = "worterbuch-common"
version = "0.38.2"
edition = "2021"
authors = ["Michael Bachmann <mbachmann@bbmsoft.net>"]
description = "Client library for Wörterbuch."
repository = "https://github.com/babymotte/worterbuch"
readme = "README.md"
license = "MIT"
keywords = ["message", "broker", "data", "base", "pubsub"]
categories = ["database"]

[features]
web = ["poem-openapi", "serde_yaml"]

[dependencies]
tokio = { version = "1.26.0", features = ["sync"] }
serde = { version = "1.0.157", features = ["derive"] }
serde_json = "1.0.94"
tungstenite = "0.20.0"

serde_yaml = { version = "0.9.22", optional = true }
poem-openapi = { version = "3.0.0", optional = true }
serde_repr = "0.1.16"
