[package]
name = "worterbuch-common"
version = "0.16.0"
edition = "2021"
authors = ["Michael Bachmann <mbachmann@bbmsoft.net>"]
description = "Client library for Wörterbuch."
repository = "https://github.com/babymotte/worterbuch"
readme = "README.md"
license = "MIT"
keywords = ["message", "broker", "data", "base", "pubsub"]
categories = ["database"]

[dependencies]
worterbuch-codec = "0.15.0"
tokio = { version = "1.20.1", features = ["sync", "rt", "io-util"] }
serde_json = "1.0.82"
tungstenite = "0.17.3"
