[package]
name = "worterbuch-common"
version = "0.35.0"
edition = "2021"
authors = ["Michael Bachmann <mbachmann@bbmsoft.net>"]
description = "Client library for Wörterbuch."
repository = "https://github.com/babymotte/worterbuch"
readme = "README.md"
license = "MIT"
keywords = ["message", "broker", "data", "base", "pubsub"]
categories = ["database"]

[dependencies]
tokio = { version = "1.26.0", features = ["sync"] }
serde = { version = "1.0.157", features = ["derive"] }
serde_json = "1.0.94"
tungstenite = "0.20.0"
poem-openapi = "3.0.0"
serde_yaml = "0.9.22"
