[package]
name = "worterbuch"
version = "0.42.1"
edition = "2021"
authors = ["Michael Bachmann <mbachmann@bbmsoft.net>"]
description = "A message broker / database hybrid."
repository = "https://github.com/babymotte/worterbuch"
readme = "../README.md"
license = "MIT"
keywords = ["message", "broker", "data", "base", "pubsub"]
categories = ["database-implementations"]

[features]
jemalloc = ["tikv-jemallocator"]
default = ["jemalloc"]

[dependencies]
worterbuch-common = { version = "0.42.0" }
tokio = { version = "1.26.0", features = ["signal", "rt-multi-thread", "fs"] }
tokio-graceful-shutdown = "0.13.0"
log = "0.4.17"
env_logger = "0.10.0"
dotenv = "0.15.0"
anyhow = "1.0.70"
serde = { version = "1.0.157", features = ["derive"] }
serde_json = "1.0.94"
uuid = { version = "1.3.0", features = ["v4"] }
clap = { version = "4.1.11", features = ["derive"] }
sha2 = "0.10.6"
hex = "0.4.3"
futures = { version = "0.3.27" }
urlencoding = "2.1.2"
poem = { version = "1.3.55", features = ["websocket", "static-files"] }
poem-openapi = { version = "3.0.0", features = ["swagger-ui"] }
tracing-subscriber = "0.3.16"
serde_yaml = "0.9.22"
hashlink = "0.8.4"
tokio-stream = "0.1.14"
[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = { version = "0.5", optional = true }

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }

[[bench]]
name = "benchmark"
harness = false
