[package]
name = "worterbuch"
version = "1.3.4"
edition = "2024"
authors = ["Michael Bachmann <mbachmann@bbmsoft.net>"]
description = "A message broker / database hybrid."
repository = "https://github.com/babymotte/worterbuch"
readme = "../README.md"
license = "AGPL-3.0-or-later"
keywords = ["message", "broker", "data", "base", "pubsub"]
categories = ["database-implementations"]
default-run = "worterbuch"

[features]
jemalloc = ["tikv-jemallocator"]
commercial = []
default = ["jemalloc"]

[dependencies]
worterbuch-common = { version = "1.0.0" }
tokio = { version = "1.26.0", features = ["rt-multi-thread", "fs"] }
tokio-graceful-shutdown = "0.16.0"
dotenvy = "0.15.7"
serde = { version = "1.0.157", features = ["derive"] }
serde_json = "1.0.94"
uuid = { version = "1.3.0", features = ["serde", "v4"] }
clap = { version = "4.1.11", features = ["derive", "env"] }
sha2 = "0.10.6"
hex = "0.4.3"
futures = { version = "0.3.27" }
poem = { version = "3.0.1", features = [
    "websocket",
    "static-files",
    "sse",
    "session",
] }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
serde_yaml = "0.9.22"
hashlink = "0.10.0"
tokio-stream = "0.1.14"
jsonwebtoken = "9.2.0"
miette = { version = "7.1.0", features = ["fancy"] }
tokio-util = "0.7.13"
tracing = "0.1.41"
flate2 = "1.1.0"
lazy_static = "1.5.0"
supports-color = "3.0.2"
base64 = "0.22.1"
hostname = "0.4.0"
opentelemetry = "0.28.0"
opentelemetry-otlp = { version = "0.28.0", features = ["grpc-tonic"] }
opentelemetry-resource-detectors = "0.7.0"
opentelemetry-semantic-conventions = "0.28.0"
opentelemetry_sdk = "0.28.0"
tracing-opentelemetry = "0.29.0"
tower-http = { version = "0.6.2", features = ["trace"] }
pprof_util = { version = "0.7.0", features = ["flamegraph"] }
mappings = "0.7.0"
regex = "1.11.1"
jemalloc_pprof = { version = "0.7.0", features = ["flamegraph"] }
inferno = "0.12.2"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = { version = "0.6.0", optional = true, features = [
    "profiling",
    "unprefixed_malloc_on_supported_platforms",
] }
jemalloc_pprof = "0.7.0"


[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all = "deny"
enum_glob_use = "deny"
# pedantic = "deny"
# nursery = "deny"
unwrap_used = "deny"
