[package]
name = "worterbuch"
version = "0.47.0"
edition = "2021"
authors = ["Michael Bachmann <mbachmann@bbmsoft.net>"]
description = "A message broker / database hybrid."
repository = "https://github.com/babymotte/worterbuch"
readme = "../README.md"
license = "AGPL-3.0-or-later"
keywords = ["message", "broker", "data", "base", "pubsub"]
categories = ["database-implementations"]
default-run = "worterbuch"

[features]
jemalloc = ["tikv-jemallocator"]
commercial = []
default = ["jemalloc"]

[dependencies]
worterbuch-common = { version = "0.47.0" }
tokio = { version = "1.26.0", features = ["rt-multi-thread", "fs"] }
tokio-graceful-shutdown = "0.15.1"
log = "0.4.17"
dotenv = "0.15.0"
anyhow = "1.0.70"
serde = { version = "1.0.157", features = ["derive"] }
serde_json = "1.0.94"
uuid = { version = "1.3.0", features = ["v4"] }
clap = { version = "4.1.11", features = ["derive"] }
sha2 = "0.10.6"
hex = "0.4.3"
futures = { version = "0.3.27" }
poem = { version = "3.0.1", features = ["websocket", "static-files", "sse"] }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
serde_yaml = "0.9.22"
hashlink = "0.9.0"
tokio-stream = "0.1.14"
jsonwebtoken = "9.2.0"
miette = { version = "7.1.0", features = ["fancy"] }
[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = { version = "0.6.0", optional = true }

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all = "deny"
enum_glob_use = "deny"
# pedantic = "deny"
# nursery = "deny"
unwrap_used = "deny"
