[package]
name = "worterbuch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["tcp", "ws"]
multithreaded = []
async = []
docker = []
tcp = ["async"]
web = ["async", "warp", "openssl", "libworterbuch/web"]
ws = ["web", "futures-util", "futures"]
graphql = [
  "libworterbuch/graphql",
  "web",
  "juniper",
  "juniper_graphql_ws",
  "juniper_warp",
  "futures",
  "async-stream",
]

[dependencies]
libworterbuch = { path = "../libworterbuch", features = ["server"] }
tokio = { version = "1.19.2", features = ["full"] }
log = "0.4.17"
env_logger = "0.9.0"
dotenv = "0.15.0"
anyhow = "1.0.57"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
uuid = { version = "1.1.1", features = ["v4"] }

juniper = { version = "0.15.9", optional = true }
juniper_graphql_ws = { version = "0.3.0", optional = true }
juniper_warp = { version = "0.7.0", features = [
  "subscriptions",
], optional = true }
warp = { version = "0.3.2", features = ["tls"], optional = true }
futures = { version = "0.3.21", optional = true }
async-stream = { version = "0.3", optional = true }
openssl = { version = "0.10.38", features = ["vendored"], optional = true }
futures-util = { version = "0.3.21", optional = true }
