[package]
name = "worterbuch"
version = "0.34.0"
edition = "2021"
authors = ["Michael Bachmann <mbachmann@bbmsoft.net>"]
description = "A message broker / database hybrid."
repository = "https://github.com/babymotte/worterbuch"
readme = "../README.md"
license = "MIT"
keywords = ["message", "broker", "data", "base", "pubsub"]
categories = ["database-implementations"]

[features]
warp = ["dep:warp"]
poem = ["dep:poem", "poem-openapi", "tracing-subscriber"]
default = ["poem"]

[dependencies]
worterbuch-common = "0.34.0"
tokio = { version = "1.26.0", features = ["signal", "rt-multi-thread", "fs"] }
log = "0.4.17"
env_logger = "0.10.0"
dotenv = "0.15.0"
anyhow = "1.0.70"
serde = { version = "1.0.157", features = ["derive"] }
serde_json = "1.0.94"
uuid = { version = "1.3.0", features = ["v4"] }
clap = { version = "4.1.11", features = ["derive"] }
sha2 = "0.10.6"
hex = "0.4.3"
futures = { version = "0.3.27" }
urlencoding = "2.1.2"

# warp feature dependencies
warp = { version = "0.3.3", optional = true }

# poem feature dependencies
poem = { version = "1.3.55", optional = true }
poem-openapi = { version = "2.0.26", features = [
    "openapi-explorer",
], optional = true }
tracing-subscriber = { version = "0.3.16", optional = true }
