[package]
name = "worterbuch"
version = "0.19.0"
edition = "2021"
authors = ["Michael Bachmann <mbachmann@bbmsoft.net>"]
description = "A message broker / database hybrid."
repository = "https://github.com/babymotte/worterbuch"
readme = "../README.md"
license = "MIT"
keywords = ["message", "broker", "data", "base", "pubsub"]
categories = ["database-implementations"]

[dependencies]
worterbuch-common = "0.19.0"
tokio = { version = "1.19.2", features = ["full"] }
log = "0.4.17"
env_logger = "0.9.0"
dotenv = "0.15.0"
anyhow = "1.0.57"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
uuid = { version = "1.1.1", features = ["v4"] }
clap = "3.2.6"
sha2 = "0.10.2"
hex = "0.4.3"
warp = { version = "0.3.2", features = ["tls"] }
futures = { version = "0.3.21" }
openssl = { version = "0.10.38", features = ["vendored"] }
