[tasks.install]
command = "cargo"
args = ["install", "--path", ".", "--features", "tcp,ws,graphql"]

[tasks.docker-login]
command = "docker"
args = ["login", "-u", "${DOCKERHUB_USERNAME}", "-p", "${DOCKERHUB_PASSWORD}"]

[tasks.docker-build]
command = "docker"
args = [
  "build",
  "-t",
  "babymotte/worterbuch:latest",
  "-t",
  "babymotte/worterbuch:${CARGO_MAKE_PROJECT_VERSION}",
  "..",
]

[tasks.docker-push-latest]
command = "docker"
args = ["push", "babymotte/worterbuch:latest"]

[tasks.docker-push-versioned]
command = "docker"
args = ["push", "babymotte/worterbuch:${CARGO_MAKE_PROJECT_VERSION}"]

[tasks.docker-push]
dependencies = ["docker-push-latest", "docker-push-versioned"]

[tasks.docker]
dependencies = ["docker-login", "docker-build", "docker-push"]
