[tasks.test-default]
command = "cargo"
args = ["test"]

[tasks.test-no-default]
command = "cargo"
args = ["test", "--no-default-features"]

[tasks.test-all-features]
command = "cargo"
args = ["test", "--all-features"]

[tasks.test-features]
dependencies = ["test-default", "test-no-default", "test-all-features"]

[tasks.install]
command = "cargo"
args = ["install", "--path", ".", "--features", "tcp,ws,graphql"]
dependencies = ["test-single-threaded"]

[tasks.docker-build]
command = "docker"
args = [
  "build",
  "-t",
  "babymotte/worterbuch:${CARGO_MAKE_PROJECT_VERSION}",
  "..",
]

[tasks.docker-build-arm]
command = "docker"
args = [
  "build",
  "-t",
  "babymotte/worterbuch:${CARGO_MAKE_PROJECT_VERSION}-armv7",
  "-f",
  "../Dockerfile.arm",
  "..",
]

[tasks.docker-push]
command = "docker"
args = ["push", "babymotte/worterbuch:${CARGO_MAKE_PROJECT_VERSION}"]

[tasks.docker-push-arm]
command = "docker"
args = ["push", "babymotte/worterbuch:${CARGO_MAKE_PROJECT_VERSION}-armv7"]

[tasks.docker]
dependencies = [
  # "docker-build",
  "docker-build-arm",
  # "docker-push",
  "docker-push-arm",
]
