[tasks.test-multi-threaded]
command = "cargo"
args = [
  "test",
  "--no-default-features",
  "--features",
  "tcp,ws,graphql,async,multithreaded",
]

[tasks.test-single-threaded]
command = "cargo"
args = ["test", "--no-default-features", "--features", "tcp,ws,graphql,async"]

[tasks.test-features]
dependencies = ["test-multi-threaded", "test-single-threaded"]

[tasks.install]
command = "cargo"
args = ["install", "--path", ".", "--features", "tcp,ws,graphql"]

[tasks.docker-build]
command = "docker"
args = [
  "build",
  "-t",
  "babymotte/worterbuch:latest",
  "-t",
  "babymotte/worterbuch:${CARGO_MAKE_PROJECT_VERSION}",
  "..",
]

[tasks.docker-push-latest]
command = "docker"
args = ["push", "babymotte/worterbuch:latest"]

[tasks.docker-push-versioned]
command = "docker"
args = ["push", "babymotte/worterbuch:${CARGO_MAKE_PROJECT_VERSION}"]

[tasks.docker-push]
dependencies = ["docker-push-latest", "docker-push-versioned"]

[tasks.docker]
dependencies = ["docker-build", "docker-push"]
