[package]
name = "libworterbuch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
tokio = { version = "1.19.2", features = [] }

[features]
default = ["async", "client", "tcp"]
client = []
server = []
tcp = []
ws = []
async = []
web = []
graphql = []

[dev-dependencies]
tokio-test = "0.4.2"
