[tasks.test-server]
command = "cargo"
args = ["test", "--no-default-features", "--features", "server,tcp,ws,graphql"]

[tasks.test-server-sync]
command = "cargo"
args = ["test", "--no-default-features", "--features", "server"]

[tasks.test-client-tcp]
command = "cargo"
args = ["test", "--no-default-features", "--features", "client,tcp"]

[tasks.test-client-ws]
command = "cargo"
args = ["test", "--no-default-features", "--features", "client,ws"]

[tasks.test-client-graphql]
command = "cargo"
args = ["test", "--no-default-features", "--features", "client,graphql"]

[tasks.test-client-sync]
command = "cargo"
args = ["test", "--no-default-features", "--features", "client"]

[tasks.test-features]
dependencies = [
  "test-server",
  "test-server-sync",
  "test-client-tcp",
  "test-client-ws",
  "test-client-graphql",
  "test-client-sync",
]
