[tasks.test-all-async]
command = "cargo"
args = ["test", "--no-default-features", "--features", "tcp,ws,graphql"]

[tasks.test-sync]
command = "cargo"
args = ["test", "--no-default-features"]

[tasks.test-features]
dependencies = ["test-all-async", "test-sync"]

[tasks.docker]

[tasks.install]
