[tasks.test-default]
command = "cargo"
args = ["test"]

[tasks.test-no-default]
command = "cargo"
args = ["test", "--no-default-features"]

[tasks.test-all-features]
command = "cargo"
args = ["test", "--all-features"]

[tasks.test-features]
dependencies = ["test-default", "test-no-default", "test-all-features"]

[tasks.docker]

[tasks.install]
