name: Build test

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ${{ matrix.image }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            image: ubuntu-24.04
            ext: ""
            target-path: ""
          - target: aarch64-unknown-linux-gnu
            image: ubuntu-24.04-arm
            ext: ""
            target-path: ""
          - target: arm-unknown-linux-gnueabihf
            image: ubuntu-24.04-arm
            ext: "/arm-unknown-linux-gnueabihf"
            target-path: ""
          - target: armv7-unknown-linux-gnueabihf
            image: ubuntu-24.04-arm
            ext: "/armv7-unknown-linux-gnueabihf"
            target-path: ""
          - target: x86_64-pc-windows-msvc
            image: windows-2022
            ext: ".exe"
            target-path: ""
          - target: aarch64-apple-darwin
            image: macos-latest
            ext: ""
            target-path: ""
          - target: x86_64-apple-darwin
            image: macos-15
            ext: ""
            target-path: ""

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: wb-${{ runner.os }}-cargo
          key: wb-${{ runner.os }}-cargo

      - name: Build
        run: cargo build --release

      - name: Package Binaries
        uses: vimtor/action-zip@v1
        with:
          files: target/release/worterbuch${{ matrix.ext }} target${{ matrix.target-path }}/release/wbdel${{ matrix.ext }} target/release/wbget${{ matrix.ext }} target/release/wbjson${{ matrix.ext }} target/release/wbls${{ matrix.ext }} target/release/wblssub${{ matrix.ext }} target/release/wbpdel${{ matrix.ext }} target/release/wbpget${{ matrix.ext }} target/release/wbpls${{ matrix.ext }} target/release/wbpsub${{ matrix.ext }} target/release/wbpub${{ matrix.ext }} target/release/wbpubs${{ matrix.ext }} target/release/wbset${{ matrix.ext }} target/release/wbsets${{ matrix.ext }} target/release/wbsub${{ matrix.ext }}
          dest: worterbuch-${{ matrix.target }}.zip
